apiVersion: v1
kind: Secret
metadata:
  name: shoppulse-secrets
  namespace: shoppulse
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME"
  REDIS_URL: "REPLACE_ME"
  SERVICE_BUS_CONNECTION_STRING: "REPLACE_ME"
